Repository auto-wallpaper/auto-wallpaper, pull requests merged in 2024-03, with the labels that each got.

#16 chore: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: maintenance

#17 chore: add vercel turbo tokens to tauri-release workflow
  .github/workflows/tauri-release.yml
Labels: maintenance

#18 add better prompts
  09ab4efa-104d-4187-8433-bf2219cdfbc2.jpeg
  1b8969f5-7eb8-475d-9110-e32fa4f1f5a3.jpeg
  267f3704-7243-449f-ba68-9df5e442d619.jpeg
  27b0af07-44c6-4874-a777-31fac41404dc.jpeg
  2d2688c7-b6df-497a-93a3-832859c841eb.jpeg
  35061ddc-dda3-4770-8ebb-9cd24e3cce24.jpeg
  5f2f6b6b-d084-4df2-944d-a8bd26383473.jpeg
  5fe9d172-de08-4890-aa85-5714e3559c38.jpeg
  636734c5-f880-4112-b29d-2702d96d43b7.jpeg
  6642d723-487c-4c5d-93e2-c467ccbf3acb.jpeg
  66ed4bd5-3156-4048-96bb-64962d044d48.jpeg
  77e350a9-6542-4d61-b9b5-5144e16f6d73.jpeg
  866794c0-d2d9-4c42-9da8-45cfff5de4f8.jpeg
  8f469b73-82d1-437e-8af2-63456121743a.jpeg
  9266e7b7-068a-4774-a1e5-d824282d16b5.jpeg
  a940587b-5d31-43b1-8335-edd93c6488a5.jpeg
  a9697008-1906-4947-8cdb-66a187419bbb.jpeg
  b4299ff0-5038-4716-a138-5bc2c351dcb0.jpeg
  bf34a964-24df-441b-a048-77f2258e5723.jpeg
  data.json
  e3e8b737-b49a-49a3-ab83-4f5ef31a946c.jpeg
Labels: gallery

#20 Update README.md
  README.md
Labels: documentation

#21 Fix initial errors
  apps/tauri-app/src-tauri/src/libs/store/mod.rs
  apps/tauri-app/src-tauri/src/main.rs
  apps/tauri-app/src/app/_components/Layout/components/Titlebar/index.tsx
  apps/tauri-app/src/app/settings/_components/Form/components/Geocoding/index.tsx
  apps/tauri-app/src/lib/PromptEngine/index.ts
  apps/tauri-app/src/stores/temp.ts
  apps/tauri-app/src/stores/user.ts
Labels: bug

#23 chore: improve logs and bug fixes
  .commitlintrc.json
  apps/tauri-app/src-tauri/src/commands/wallpaper.rs
  apps/tauri-app/src-tauri/src/commands/wallpaper_engine.rs
  apps/tauri-app/src-tauri/src/libs/wallpaper_engine/mod.rs
  apps/tauri-app/src-tauri/src/main.rs
Labels: maintenance

#26 docs: fix tauri prerequisites url
  README.md
Labels: documentation

#28 chore: add prompt engine to the rust code
  Cargo.lock
  apps/tauri-app/src-tauri/Cargo.toml
  apps/tauri-app/src-tauri/src/commands/mod.rs
  apps/tauri-app/src-tauri/src/commands/prompt.rs
  apps/tauri-app/src-tauri/src/libs/mod.rs
  apps/tauri-app/src-tauri/src/libs/prompt_engine/mod.rs
  apps/tauri-app/src-tauri/src/libs/wallpaper_engine/mod.rs
  apps/tauri-app/src-tauri/src/libs/wallpaper_engine/structs.rs
  apps/tauri-app/src-tauri/src/main.rs
  apps/tauri-app/src-tauri/src/states/mod.rs
  apps/tauri-app/src-tauri/src/states/prompt_engine.rs
  apps/tauri-app/src-tauri/src/tray.rs
  apps/tauri-app/src/app/_components/PromptCard/index.tsx
  apps/tauri-app/src/app/_components/PromptsGrid/components/NewPrompt/index.tsx
  apps/tauri-app/src/app/_components/PromptsGrid/components/PromptCard/components/Actions/components/EditAction/index.tsx
  apps/tauri-app/src/app/_components/PromptsGrid/components/PromptCard/components/Actions/index.tsx
  apps/tauri-app/src/app/_components/PromptsGrid/index.tsx
  apps/tauri-app/src/app/settings/_components/Form/index.tsx
  apps/tauri-app/src/lib/PromptEngine/index.ts
  apps/tauri-app/src/stores/makeStore.ts
  apps/tauri-app/src/stores/user.ts
  apps/tauri-app/src/utils/commands.ts
Labels: feature

#29 fix(tauri): make geolocation admin fields optional in schema
  apps/tauri-app/src/stores/user.ts
Labels: bug

#30 Improve log system
  Cargo.lock
  apps/tauri-app/src-tauri/Cargo.toml
  apps/tauri-app/src-tauri/src/main.rs
  apps/tauri-app/src/app/_components/Layout/index.tsx
  apps/tauri-app/src/stores/user.ts
  apps/tauri-app/src/utils/fetchCookie.ts
  apps/tauri-app/src/utils/log.ts
Labels: maintenance
